# [[plugins]]
# hook_add = '''
# augroup MyAutoCmd
#   autocmd!
# augroup END
# autocmd MyAutoCmd VimEnter * ++nested colorscheme onedark
# '''
# hook_post_source = '''
# lua <<EOD
# require('onedark').setup {
#     style = 'darker'
# }
# EOD
# '''
# repo = 'navarasu/onedark.nvim'
# merged = 0

# [[plugins]]
# hook_add = '''
# colorscheme iceberg
# "let g:onedark_termcolors=256
# "autocmd MyAutoCmd VimEnter * ++nested colorscheme iceberg
# '''
# repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'projekt0n/github-nvim-theme'
hook_add = '''
lua <<EOF
-- Example config in Lua
require("github-theme").setup({
  options = {
    styles = {
      functions = "Italic"
    },
    darken = {
      sidebars = {
        list = {"qf", "vista_kind", "terminal", "packer"}
      }
    }
  },

  -- Change the "hint" color to the "orange" color, and make the "error" color bright red
  -- colors = {hint = "orange", error = "#ff0000"},

  -- Overwrite the highlight groups
})

vim.cmd.colorscheme('github_dark_dimmed')
EOF

'''

# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = "nvim-tree/nvim-web-devicons"

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
depends = ["nvim-treesitter"]
hook_post_source = '''
lua <<EOF
require("indent_blankline").setup {
    -- for example, context is off by default, use this to turn it on
    show_current_context = true,
    show_current_context_start = true,
}
EOF
'''
