# [[plugins]]
# hook_add = '''
# augroup MyAutoCmd
#   autocmd!
# augroup END
# autocmd MyAutoCmd VimEnter * ++nested colorscheme onedark 
# '''
# hook_post_source = '''
# lua <<EOD
# require('onedark').setup {
#     style = 'darker'
# }
# EOD
# '''
# repo = 'navarasu/onedark.nvim'
# merged = 0
# 

[[plugins]]
hook_post_source = '''
lua << EOF
require('lualine').setup {
    options = {
        theme = 'iceberg_dark'
    }
}
EOF
'''
merged = 0
#on_source = ['onedark.nvim']
repo = 'nvim-lualine/lualine.nvim'

[[plugins]]
hook_add = '''
augroup MyAutoCmd
  autocmd!
augroup END

"colorscheme onedark
let g:onedark_termcolors=256
autocmd MyAutoCmd VimEnter * ++nested colorscheme iceberg
'''
repo = 'cocopon/iceberg.vim'

#[[plugins]]
#hook_add = '''
#augroup MyAutoCmd
#  autocmd!
#augroup END
#
#"colorscheme onedark
#let g:onedark_termcolors=256
#autocmd MyAutoCmd VimEnter * ++nested colorscheme onedark 
#'''
#repo = 'joshdick/onedark.vim'

# [[plugins]]
# hook_add = '''
# source $HOME/.config/nvim/plug_confs/vim-airline.vim
# '''
# repo = 'vim-airline/vim-airline'
# 
# [[plugins]]
# depends = ['vim-airline']
# hook_add = '''
# let g:airline_theme = "onedark"
# '''
# repo = 'vim-airline/vim-airline-themes'

# [[plugins]]
# repo = 'ayu-theme/ayu-vim'
# hook_add = '''
# set termguicolors 
# let ayucolor="mirage"
# colorscheme ayu
# '''

[[plugins]]
repo = 'crispgm/nvim-tabline'
hook_post_source = """
lua <<EOF
require("tabline").setup{}
EOF
"""


[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# [[plugins]]
# repo = 'lukas-reineke/indent-blankline.nvim'
# hook_post_source = '''
# lua <<EOF
# require("indent_blankline").setup {
#     -- for example, context is off by default, use this to turn it on
#     show_current_context = true,
#     show_current_context_start = true,
# }
# EOF
# '''
