[[plugins]]
hook_add = '''
colorscheme onedark
let g:onedark_termcolors=256
'''
repo = 'joshdick/onedark.vim'

[[plugins]]
hook_add = '''
" https://qiita.com/park-jh/items/557a9d5b470947aef2f5
" Powerline系フォントを利用する
set laststatus=2
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline_theme = 'onedark'
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '☰'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.maxlinenr = '㏑'
let g:airline_symbols.branch = '⎇' 
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = '∄'
let g:airline_symbols.whitespace = 'Ξ'

" powerline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = '☰ '
let g:airline_symbols.maxlinenr = ''
'''
repo = 'vim-airline/vim-airline'

[[plugins]]
hook_add = '''
let g:airline_theme = "onedark"
'''
repo = 'vim-airline/vim-airline-themes'

# [[plugins]]
# repo = 'ayu-theme/ayu-vim'
# hook_add = '''
# set termguicolors 
# let ayucolor="mirage"
# colorscheme ayu
# '''
