#: [[plugins]] # 置換のプレビュー
# repo = 'markonm/traces.vim'

# [[plugins]]
# repo = 'tomtom/tcomment_vim'

[[plugins]] # ファイラー
repo = 'preservim/nerdtree'

# [[plugins]] 
# repo = 'tpope/vim-surround'

[[plugins]]
repo = 'lervag/vimtex'
hook_source = '''
    set shellslash
    let g:vimtex_compiler_progname = 'nvr'  
    let g:vimtex_view_general_viewer = 'evince'
    let g:vimtex_compiler_latexmk = {
    \     'background': 1,
    \     'build_dir': '',
    \     'executable': 'latexmk',
    \     'options': [
    \     '-lualatex',
    \    ],
    \}
    autocmd FileType latex nnoremap <A-l> :!latexindent -s -w "%:p"<CR>
    autocmd FileType tex nnoremap <A-l> :!latexindent -s -w "%:p"<CR>
    autocmd FileType plaintex nnoremap <A-l> :!latexindent -s -w "%:p"<CR>
'''

