[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
hook_add = '''
source $HOME/.config/nvim/plug_confs/ddc.vim
'''
repo = 'Shougo/ddc.vim'

[[plugins]]
hook_add = '''

'''
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'delphinus/ddc-treesitter'

[[plugins]]
repo = 'matsui54/ddc-ultisnips'

[[plugins]]
repo = 'gamoutatsumi/ddc-emoji'

[[plugins]]
hook_add = '''
" check with C-k and key result
" vim help key-notaion
nnoremap <A-l> :LspDocumentFormat<CR>
noremap <S-F6> :LspRename<CR>
noremap <F18> :LspRename<CR>
let g:lsp_fold_enabled = 0
let g:lsp_document_highlight_enabled = 0
'''
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
hook_add = '''
let g:lexima_enable_endwise_rules = 1
let g:lexima_enable_newline_rules = 1

call lexima#add_rule({
            \ 'char': '$', 
            \ 'input_after': '$',
            \ 'filetype': 'latex'
            \ })
call lexima#add_rule({
            \ 'char': '$',
            \ 'at': '\%#\$',
            \ 'leave': 1,
            \ 'filetype': 'latex'
            \ })
call lexima#add_rule({
            \ 'char': '<BS>',
            \ 'at': '\$\%#\$',
            \ 'delete': 1,
            \ 'filetype': 'latex'
            \ })
call lexima#add_rule({
            \ 'char': '「', 
            \ 'input_after': '」',
            \ 'filetype': 'markdown'
            \ })
call lexima#add_rule({
            \ 'char': '『', 
            \ 'input_after': '』',
            \ 'filetype': 'markdown'
            \ })
call lexima#add_rule({
            \ 'char': '<BS>',
            \ 'at': '「\%#」',
            \ 'delete': 1,
            \ 'filetype': 'markdown'
            \ })
call lexima#add_rule({
            \ 'char': '<BS>',
            \ 'at': '『\%#』',
            \ 'delete': 1,
            \ 'filetype': 'markdown'
            \ })
'''
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
hook_add = '''
nnoremap <F22> :QuickRun<CR>
nnoremap <S-F10> :QuickRun<CR>
'''
repo = 'thinca/vim-quickrun'

[[plugins]]
hook_add = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_math = 0
let g:vim_markdown_new_list_item_indent = 2
let g:vim_markdown_auto_iinsert_bullets= 0 
let g:vim_markdown_conceal = 0
'''
on_ft = ['markdown']
repo = 'preservim/vim-markdown'

[[plugins]] # gitの表示
repo = 'airblade/vim-gitgutter'

[[plugins]]
hook_add = '''
nnoremap <F5> :UndotreeToggle<CR>
'''
repo = 'mbbill/undotree'

[[plugins]]
depends = ['context_filetype_vim']
repo = 'osyo-manga/vim-precious'
[[plugins]]
hook_post_source = '''
source $HOME/.config/nvim/plug_confs/context_filetype.vim
'''
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = '907th/vim-auto-save'
# repo = 'vim-scripts/vim-auto-save'
hook_add = '''
    if expand("%:p") =~ 'COMMIT_EDITMSG'
    else
        let g:auto_save = 1
    endif
    let g:auto_save_in_insert_mode = 0  " do not save while in insert mode
'''

[[plugins]]
hook_add = '''
augroup MyAutoCmd
  autocmd!
augroup END

"colorscheme onedark
let g:onedark_termcolors=256
autocmd MyAutoCmd VimEnter * ++nested colorscheme onedark 
'''
repo = 'joshdick/onedark.vim'

[[plugins]]
hook_add = '''
source $HOME/.config/nvim/plug_confs/vim-airline.vim
'''
repo = 'vim-airline/vim-airline'

[[plugins]]
depends = ['vim-airline']
hook_add = '''
let g:airline_theme = "onedark"
'''
repo = 'vim-airline/vim-airline-themes'

# [[plugins]]
# repo = 'ayu-theme/ayu-vim'
# hook_add = '''
# set termguicolors 
# let ayucolor="mirage"
# colorscheme ayu
# '''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
hook_add = '''
let g:UltiSnipsSnippetDirectories = [$HOME . "/.config/nvim/ultisnips"]
'''
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
hook_post_source = '''
nnoremap <M-1> :NERDTreeToggle<CR>
'''
repo = 'preservim/nerdtree'

[[plugins]]
build = './install --all'
merged = 0
repo = 'junegunn/fzf'

[[plugins]]
depends = ['fzf']
hook_post_source = '''
nnoremap <M-F> :Rg<CR>
'''
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'tpope/vim-surround'
