[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
hook_add = '''
source $HOME/.config/nvim/plug_confs/ddc.vim
'''
repo = 'Shougo/ddc.vim'

# [[plugins]]
# repo = 'Shougo/pum.vim'
# hook_add = '''
# '''

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/deoppet.nvim'

[[plugins]]
hook_add = '''
" check with C-k and key result
" vim help key-notaion
nnoremap <A-l> :LspDocumentFormat<CR>
noremap <S-F6> :LspRename<CR>
noremap <F18> :LspRename<CR>
let g:lsp_fold_enabled = 0
'''
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

#
# from lazy
#
[[plugins]]
hook_add = '''
let g:lexima_enable_endwise_rules = 1
'''
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
hook_add = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_math = 0
let g:vim_markdown_new_list_item_indent = 2
let g:vim_markdown_auto_iinsert_bullets= 0 
let g:vim_markdown_conceal = 0
'''
on_ft = ['markdown']
repo = 'preservim/vim-markdown'

[[plugins]] # gitの表示
repo = 'airblade/vim-gitgutter'

[[plugins]]
hook_add = '''
    nnoremap <F5> :UndotreeToggle<CR>
'''
repo = 'mbbill/undotree'

[[plugins]]
depends = ['Shougo/context_filetype_vim']
repo = 'osyo-manga/vim-precious'
[[plugins]]
hook_post_source = '''
source $HOME/.config/nvim/plug_confs/context_filetype.vim
'''
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = '907th/vim-auto-save'
# repo = 'vim-scripts/vim-auto-save'
hook_add = '''
    if expand("%:p") =~ 'COMMIT_EDITMSG'
    else
        let g:auto_save = 1
    endif
    let g:auto_save_in_insert_mode = 0  " do not save while in insert mode
'''

[[plugins]]
build = 'sh -c "cd app && yarn install"'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
repo = 'iamcco/markdown-preview.nvim'


[[plugins]]
hook_post_update = '''
source $HOME/.config/nvim/plug_confs/nvim-treesitter.vim
'''
repo = 'nvim-treesitter/nvim-treesitter'


[[plugins]]
hook_add = '''
augroup MyAutoCmd
  autocmd!
augroup END

"colorscheme onedark
let g:onedark_termcolors=256
autocmd MyAutoCmd VimEnter * ++nested colorscheme onedark 
'''
repo = 'joshdick/onedark.vim'

[[plugins]]
hook_add = '''
source $HOME/.config/nvim/plug_confs/vim-airline.vim
'''
repo = 'vim-airline/vim-airline'

[[plugins]]
depends = ['vim-airline/vim-airline']
hook_add = '''
let g:airline_theme = "onedark"
'''
repo = 'vim-airline/vim-airline-themes'

# [[plugins]]
# repo = 'ayu-theme/ayu-vim'
# hook_add = '''
# set termguicolors 
# let ayucolor="mirage"
# colorscheme ayu
# '''

[[plugins]]
repo = 'tpope/vim-fugitive'
