[[plugins]]
depends = ['denops.vim']
hook_source = '''
source $HOME/.config/nvim/plug_confs/ddc.vim
'''
on_event = ['insertEnter']
repo = 'Shougo/ddc.vim'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-around'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
on_source = 'ddc.vim'
repo = 'tani/ddc-fuzzy'

[[plugins]]
on_source = 'ddc.vim'
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
depends = ['ddc.vim', 'vim-lsp']
on_source = ['ddc.vim', 'vim-lsp']
repo = 'shun/ddc-vim-lsp'

[[plugins]]
on_source = 'ddc.vim'
repo = 'LumaKernel/ddc-file'

[[plugins]]
on_source = 'ddc.vim'
repo = 'delphinus/ddc-treesitter'

[[plugins]]
depends = ['ultisnips']
on_source = 'ddc.vim'
repo = 'matsui54/ddc-ultisnips'

[[plugins]]
on_source = 'ddc.vim'
repo = 'gamoutatsumi/ddc-emoji'
