[[plugins]]
depends = ['denops.vim']
repo = 'Shougo/ddu.vim'
# on_source = ['denops.vim']
hook_source = '''
let s:patch_global = {}
let s:sourceOptions = {}
let s:sourceParams = {}
let s:uiParams = {}
let s:kindOptions = {}
let s:patch_global.ui = 'ff'
let s:sourceOptions._ = {
      \ 'ignoreCase': v:true,
      \ 'matchers': ['matcher_fzf'],
      \ }
let s:sourceOptions.file_old = {
      \ 'matchers': ['matcher_fzf', 'matcher_relative', 'matcher_hidden'],
      \ }
let s:sourceOptions.file_external = {
      \ 'matchers': ['matcher_fzf', 'matcher_hidden'],
      \ }
let s:sourceParams.file_external = {
      \ 'cmd': ['git', 'ls-files', '-co', '--exclude-standard'],
      \ }
let s:uiParams.ff = {
    \ 'split': has('nvim') ? 'floating' : 'horizontal',
    \ 'prompt': '> ',
    \ }
let s:kindOptions.file = {
      \ 'defaultAction': 'open',
      \ }
let s:kindOptions.readme_viewer = {
      \ 'defaultAction': 'open',
      \ }
let s:kindOptions.colorscheme = {
      \ 'defaultAction': 'set',
      \ }
let s:kindOptions.help = {
      \ 'defaultAction': 'open',
      \ }
let s:patch_global.sourceOptions = s:sourceOptions
let s:patch_global.sourceParams = s:sourceParams
let s:patch_global.uiParams = s:uiParams
let s:patch_global.kindOptions = s:kindOptions
call ddu#custom#patch_global(s:patch_global)
'''

[plugins.ftplugin]
ddu-ff = '''
nnoremap <silent><buffer> <CR>
      \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <silent><buffer> <Space>
      \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <silent><buffer> i
      \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <silent><buffer> <C-l>
      \ <Cmd>call ddu#ui#ff#do_action('refreshItems')<CR>
nnoremap <silent><buffer> p
      \ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
nnoremap <silent><buffer> q
      \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
'''

ddu-ff-filter = '''
inoremap <silent><buffer> <CR>
      \ <Esc><Cmd>close<CR>
nnoremap <silent><buffer> <CR>
      \ <Cmd>close<CR>
'''

[[plugins]]
depends = ['ddu.vim']
on_cmd = ['Ddu']
repo = 'Shougo/ddu-commands.vim'

# UI

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-ui-ff'

# filters

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-filter-matcher_hidden'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-filter-matcher_relative'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
on_source = 'ddu.vim'
repo = 'yuki-yano/ddu-filter-fzf'

# kinds

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-kind-file'

# sources

[[plugins]]
on_source = 'ddu.vim'
repo = '4513echo/ddu-source-colorscheme'

[[plugins]]
on_source = 'ddu.vim'
repo = '4513echo/ddu-source-ghq'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-file'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-file_old'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-file_point'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
on_source = 'ddu.vim'
repo = 'Shougo/ddu-source-line'

[[plugins]]
on_source = 'ddu.vim'
repo = 'matsui54/ddu-source-file_external'

[[plugins]]
on_source = 'ddu.vim'
repo = 'matsui54/ddu-source-help'

[[plugins]]
on_source = 'ddu.vim'
repo = 'shun/ddu-source-buffer'

[[plugins]]
on_source = 'ddu.vim'
repo = 'shun/ddu-source-rg'
