[[plugins]]
hook_add = '''
let g:lexima_enable_endwise_rules = 1
let g:lexima_enable_newline_rules = 1
'''
on_event = ['InsertEnter']
repo = 'cohama/lexima.vim'


[[plugins]]
repo = '907th/vim-auto-save'
# repo = 'vim-scripts/vim-auto-save'
hook_add = '''
    if expand("%:p") =~ 'COMMIT_EDITMSG'
    else
        let g:auto_save = 1
    endif
    let g:auto_save_in_insert_mode = 0  " do not save while in insert mode
'''
on_event = ['InsertEnter']

[[plugins]]
build = './install --all'
merged = 0
on_cmd = ['Rg']
repo = 'junegunn/fzf'

[[plugins]]
depends = ['fzf']
hook_add = '''
nnoremap <M-F> :Rg<CR>
'''
on_source = ['fzf']
repo = 'junegunn/fzf.vim'

[[plugins]]
hook_add = '''
nnoremap <F5> :UndotreeToggle<CR>
'''
on_cmd = ['UndotreeToggle']
repo = 'mbbill/undotree'

[[plugins]]
hook_add = '''
nnoremap <F22> :QuickRun<CR>
nnoremap <S-F10> :QuickRun<CR>
'''
on_cmd = [':QuickRun']
repo = 'thinca/vim-quickrun'

[[plugins]]
hook_add = '''
nnoremap <M-1> :NERDTreeToggle<CR>
'''
on_cmd = ['NERDTreeToggle']
repo = 'preservim/nerdtree'


[[plugins]]
depends = 'denops'
hook_post_source = '''
nmap  <C-a>  <Plug>(dps-dial-increment)
nmap  <C-x>  <Plug>(dps-dial-decrement)
xmap  <C-a>  <Plug>(dps-dial-increment)
xmap  <C-x>  <Plug>(dps-dial-decrement)
xmap g<C-a> g<Plug>(dps-dial-increment)
xmap g<C-x> g<Plug>(dps-dial-decrement)
'''
on_source = ['denops']
repo = 'monaqa/dps-dial.vim'

[[plugins]]
depends = ['onedark.nvim']
hook_post_source = '''
lua << EOF
require('lualine').setup {
    options = {
        theme = 'onedark'
    }
}
EOF
'''
merged = 0
on_source = ['onedark.nvim']
repo = 'nvim-lualine/lualine.nvim'
