#[[plugins]]
#repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
" https://qiita.com/shinespark/items/1d6ec0de89aa537da505
let g:quickrun_config = {
    "python": {
        "command": "python3"
    },
}
'''

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
" clang formatの設定
autocmd FileType c ClangFormatAutoEnable
'''

# [[plugins]]
# repo = 'vim-autopep8'

[[plugins]]
repo = "airblade/vim-gitgutter"

