[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # gitの表示
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
depends = ['context_filetype_vim']
hook_post_source = '''
let g:precious_enable_switchers = {
            \   "markdown": {
            \       "setfiletype": 0
            \       }
            \   }
'''
repo = 'osyo-manga/vim-precious'


[[plugins]]
hook_post_source = '''
nnoremap <M-1> :NERDTreeToggle<CR>
'''
repo = 'preservim/nerdtree'

[[plugins]]
hook_post_source = '''
map <silent> w <Plug>CamelCaseMotion_w
map <silent> b <Plug>CamelCaseMotion_b
map <silent> e <Plug>CamelCaseMotion_e
map <silent> ge <Plug>CamelCaseMotion_ge
sunmap w
sunmap b
sunmap e
sunmap ge
'''
repo = 'bkad/CamelCaseMotion'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
depends = 'denops'
hook_post_source = '''
nmap  <C-a>  <Plug>(dps-dial-increment)
nmap  <C-x>  <Plug>(dps-dial-decrement)
xmap  <C-a>  <Plug>(dps-dial-increment)
xmap  <C-x>  <Plug>(dps-dial-decrement)
xmap g<C-a> g<Plug>(dps-dial-increment)
xmap g<C-x> g<Plug>(dps-dial-decrement)
'''
on_source = ['denops']
repo = 'monaqa/dps-dial.vim'
