[ftplugin]
go = '''
set tabstop=4
set nowrap
'''
markdown = '''
setlocal wrap
setlocal tabstop=2
setlocal shiftwidth=2
'''

[[plugins]]
hook_source = '''
    set shellslash
    let g:vimtex_compiler_progname = 'nvr'  
    let g:vimtex_view_general_viewer = 'evince'
    let g:vimtex_compiler_latexmk = {
    \     'background': 1,
    \     'build_dir': '',
    \     'executable': 'latexmk',
    \     'options': [
    \     '-lualatex',
    \    ],
    \}
'''
on_ft = ['plaintex', 'tex']
repo = 'lervag/vimtex'

[[plugins]]
build = 'sh -c "cd app && yarn install"'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
repo = 'iamcco/markdown-preview.nvim'

[[plugins]]
hook_add = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_math = 0
let g:vim_markdown_new_list_item_indent = 2
let g:vim_markdown_auto_iinsert_bullets= 0 
let g:vim_markdown_conceal = 0
'''
on_ft = ['markdown']
repo = 'preservim/vim-markdown'
