[[plugins]]
hook_post_source = '''
"source $HOME/.config/nvim/plug_confs/nvim-treesitter.vim
lua <<EOF
require'nvim-treesitter.configs'.setup {
  -- One of "all", "maintained" (parsers with maintainers), or a list of languages
  ensure_installed = "maintained",

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    -- list of language that will be disabled
    disable = {"vim", "lua"},

    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
  rainbow = {
    enable = true,
    -- disable = { "jsx", "cpp" }, list of languages you want to disable the plugin for
    extended_mode = true, -- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
    max_file_lines = nil, -- Do not enable for files with more than n lines, int
    -- colors = {}, -- table of hex strings
    -- termcolors = {} -- table of colour name strings
    }
}
EOF
'''
merged = 0
on_event = 'VimEnter'
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
depends = ['nvim-treesitter']
on_source = 'nvim-treesitter'
repo = 'p00f/nvim-ts-rainbow'

[[plugins]]
hook_add = '''
" check with C-k and key result
" vim help key-notaion
nnoremap <A-l> :LspDocumentFormat<CR>
noremap <S-F6> :LspRename<CR>
noremap <F18> :LspRename<CR>
let g:lsp_fold_enabled = 0
let g:lsp_document_highlight_enabled = 0
'''
on_event = 'VimEnter'
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
depends = ['vim-lsp']
on_source = ['vim-lsp']
repo = 'mattn/vim-lsp-settings'

[[plugins]]
depends = ['vim-lsp']
on_source = ['vim-lsp']
repo = 'mattn/vim-lsp-icons'

[[plugins]]
hook_add = '''
let g:UltiSnipsSnippetDirectories = [$HOME . "/.config/nvim/ultisnips"]
'''
repo = 'SirVer/ultisnips'
